name: Docs in GitHub Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  release:
    types: [created]
    branches:
      - 'master'
  workflow_dispatch:

env:
  FORCE_COLOR: "1"  # Make tools pretty.
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"
  PYTHON_LATEST: "3.11"

jobs:
  build-docs:
    name: "Build docs"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_LATEST }}
        cache: pip
        cache-dependency-path: |
          setup.py
          requirements-doc.txt
    - name: "Install runtime dependencies"
      run: |
        pip install -U pip setuptools wheel
        pip install -U -r requirements-doc.txt
    - name: "Install doc build deps and build with Sphinx"
      run: make doc
    - name: "Upload artifacts"
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload built docs
        path: "./docs/_build/html/"
  publish-docs:
    name: "Publish the docs"
    needs: build-docs
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: "Deploy to GitHub Pages"
      uses: actions/deploy-pages@v2
      id: deployment
